### ISSUE TITLE
use fennel as library

### ISSUE THREAD

**Issue by Amenocy** [LordEidi/fennel.js#9]
hi , 
how i can use fennel as a library ?

**Comment by LordEidi** [comment]
Hi

I am not sure I follow your question. You want to use which part of fennel as what kind of library?

**Comment by tobiasmuecksch** [comment]
I guess he wishes to have a library on which he can build his own CardDAV Server.

In my opinion that would be handy. For example: I have a mongoDB holding information about users in my system and I want to sync these users into my ContactBook. When a contact is changed in the ContactBook I want some events to be triggered. As fennel is a stand alone server I guess it won't help me creating my own cardDAV service.

**Comment by LordEidi** [comment]
Why don't you just feed your data into the database directly? Without going through DAV? At the end, fennel is just a transport for Card and Calendar data. As long as you respect the database schema and update fields like update time etc., that should work.

**Comment by tobiasmuecksch** [comment]
I guess I will try it this way.

**Comment by LordEidi** [comment]
I'd be interested to hear any success or fail story.

**Comment by mdarveau** [comment]
I am also tackling this to expose sport team calendar for maligue.ca. I will let you know how it goes. For the moment, I am just trying to get the server running with the provided auth and persistence and it does not work (see https://github.com/LordEidi/fennel/issues/11 and https://github.com/LordEidi/fennel/issues/12)

**Comment by LordEidi** [comment]
Regarding #11, that one is fixed and closed. Let's find the problem for #12. And thanks for giving fennel a chance :)

**Comment by mdarveau** [comment]
I started refactoring the code to use express instead of node's http. The advantage is that the middleware could then be plugged into existing express installations. It is a WIP but it's functional: https://github.com/mdarveau/fennel/commit/0f87dc1faeaac411ccba415d4194f850af639335

As a bonus, I configured winston so we can get the full HTTP log when needed.

**Comment by rexfng** [comment]
I agree, my company is looking to integrate it to our server. Having it as an express middleware is valuable. @mdarveau  I'm up for contributing to that express-middleware proposition. If OP @LordEidi does not support that, let me know when you spun off as a separate project.

**Comment by LordEidi** [comment]
I am not getting the reason why you would want to introduce more middleware to fennel? What is the benefit of running it inside something else?

**Comment by LordEidi** [comment]
Oh and @rexfng please keep in mind that Fennel is released under the AGPLv3 when you integrate it into something else...

**Comment by rexfng** [comment]
@LordEidi the reason would be speed of development. I would say we are already thankful for the fennel library. Thanks for reminding about it being released under AGPLv3. Whatever we work on on top of this will be available to the general public.

**Comment by LordEidi** [comment]
I am still not getting it, sorry. What exactly would be quicker in development?
